name: test

on:
  push: 
    branches:
      - 'main'
      - 'releases/**'
      - 'cicd-aws'
  pull_request:
    paths-ignore: [ '*.md' ]
    branches:
      - main
      - '**'

permissions:
  id-token: write
  contents: read

jobs:
  stresstest-build-test:
    runs-on: ubuntu-latest
    container: seconddinner/build:0.0.2
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0